<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="36715" started-at="2016-04-17T07:40:26Z" finished-at="2016-04-17T07:41:02Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="36715" started-at="2016-04-17T07:40:26Z" finished-at="2016-04-17T07:41:02Z">
      <class name="com.test.pack.test1">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.test.pack.test1@66d33a]" name="setup" is-config="true" duration-ms="33215" started-at="2016-04-17T13:10:26Z" finished-at="2016-04-17T13:10:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testpage()[pri:0, instance:com.test.pack.test1@66d33a]" name="testpage" duration-ms="3340" started-at="2016-04-17T13:10:59Z" finished-at="2016-04-17T13:11:02Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.base.pack.BrowserEventManager.screenshot(BrowserEventManager.java:737)
	at com.test.pack.test1.testpage(test1.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testpage -->
        <test-method status="PASS" signature="Testresult(org.testng.ITestResult)[pri:0, instance:com.test.pack.test1@66d33a]" name="Testresult" is-config="true" duration-ms="10" started-at="2016-04-17T13:11:02Z" finished-at="2016-04-17T13:11:02Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testpage status=FAILURE method=test1.testpage()[pri:0, instance:com.test.pack.test1@66d33a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Testresult -->
      </class> <!-- com.test.pack.test1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
